name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
      - name : merge
        uses : nbrugger-tgm/merge-pr-action@v0.2.3
        with :
          token: ${{ secrets.GITHUB_TOKEN }}
          method: squash